dist: bionic

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  # https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
  - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true"
  - MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version"

stages:
  - name: build

jobs:
  include:
    - stage: build
      install: "/bin/true"
      script:
        - mvn $MAVEN_CLI_OPTS clean verify
